serialize = true
use-workspace-deps = "../../Cargo.toml"

[package]
name = "database/generated"

[types.crates]
ctypes = { path = "./database/ctypes" }

[types.mapping]
"public.blood_group" = "ctypes::BloodGroup"
"public.role" = "ctypes::Role"
"public.request_priority" = "ctypes::RequestPriority"
"public.donation_type" = "ctypes::DonationType"
