serialize = true
use-workspace-deps = "../../Cargo.toml"

[package]
name = "database"

[types]
derive-traits = ["serde::Deserialize", "utoipa::ToSchema"]

[types.crates]
ctypes = { path = "../ctypes" }

[types.mapping]
"public.blood_group" = "ctypes::BloodGroup"
"public.role" = "ctypes::Role"
"public.request_priority" = "ctypes::RequestPriority"
"public.donation_type" = "ctypes::DonationType"
