services:
  database:
    container_name: blood-donation-system-database
    image: postgres:latest
    ports:
      - 5433:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: blood-donation-system-cloudbeaver
    restart: always
    ports:
      - 8978:8978
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: blood-donation-system-qdrant
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant:/qdrant/storage
    networks:
      - network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - network

  backend:
    container_name: blood-donation-system-backend
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}

      BCRYPT__COST: ${BCRYPT_COST}
      BCRYPT__SALT: ${BCRYPT_SALT}

      EMAIL__USERNAME: ${EMAIL_USERNAME}
      EMAIL__PASSWORD: ${EMAIL_PASSWORD}

      JWT__SECRET: ${JWT_SECRET}
      JWT__EXPIRED_IN: ${JWT_EXPIRED_IN}

      REDIS__PASSWORD: ${REDIS_PASSWORD}
      REDIS__HOST: redis

      OIDC__LOGIN_REDIRECT: ${OIDC_LOGIN_REDIRECT}
      OIDC__REGISTER_REDIRECT: ${OIDC_REGISTER_REDIRECT}
      OIDC__CLIENTS__GOOGLE__CLIENT_ID: ${GOOGLE_CLIENT_ID}
      OIDC__CLIENTS__GOOGLE__CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OIDC__CLIENTS__GOOGLE__ISSUER_URL: ${GOOGLE_ISSUER_URL}
      OIDC__CLIENTS__GOOGLE__REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      OIDC__CLIENTS__MICROSOFT__CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      OIDC__CLIENTS__MICROSOFT__CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      OIDC__CLIENTS__MICROSOFT__ISSUER_URL: ${MICROSOFT_ISSUER_URL}
      OIDC__CLIENTS__MICROSOFT__REDIRECT_URL: ${MICROSOFT_REDIRECT_URL}

      RAG__QDRANT_URL: ${QDRANT_URL}
      RAG__GEMINI_API_KEY: ${GEMINI_API_KEY}
      RAG__CONTEXT_SAMPLE: ${RAG_CONTEXT_SAMPLE}
    image: ${REGISTRY}/backend:latest
    restart: always
    volumes:
      - type: bind
        source: ./docs
        target: /app/docs
    ports:
      - 3000:3000
    networks:
      - network
    profiles:
      - backend
      - deploy
  frontend:
    container_name: blood-donation-system-frontend
    image: ${REGISTRY}/frontend:latest
    environment:
      API_URL: ${API_URL}
    restart: always
    ports:
      - 3001:3000
    networks:
      - network
    profiles:
      - frontend
      - deploy
networks:
  network:
    name: blood-donation-system-network
    external: true

volumes:
  database:
    name: blood-donation-system-database
    external: true
  qdrant:
    name: blood-donation-system-qdrant
    external: true
  cloudbeaver:
    name: blood-donation-system-cloudbeaver
    driver: local
