use-workspace-deps = "../../Cargo.toml"

[package]
name = "database"

[types]
derive-traits = ["utoipa::ToSchema"]

[types.crates]
utoipa = { version = "5.3.1", features = ["chrono", "uuid"] }
ctypes = { path = "../ctypes" }

[types.mapping]
"public.blood_group" = "ctypes::BloodGroup"
"public.role" = "ctypes::Role"
"public.request_priority" = "ctypes::RequestPriority"
"public.donation_type" = "ctypes::DonationType"
"public.gender" = "ctypes::Gender"
"public.blood_component" = "ctypes::BloodComponent"
"public.appointment_status" = "ctypes::AppointmentStatus"
"public.chat_role" = "ctypes::ChatRole"
"pg_catalog.date" = "chrono::NaiveDate"
"pg_catalog.timestamptz" = "chrono::DateTime<chrono::FixedOffset>"
