database_url = "postgres://user:password@host/database"
port = 3000

[bcrypt]
cost = 10
salt = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[jwt]
secret = "secret"
expired_in = 86400
token_key = "token"

[open_id_connect]
frontend_redirect_url = "http://localhost:3001"
oauth2_redirect_url = "http://localhost:3000/auth"

[open_id_connect.clients.google]
client_id = ""
client_secret = ""
issuer_url = ""
redirect_utl = ""
