database_url = "postgres://user:password@host/database"

[bcrypt]
cost = 10
salt = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[email]
username = "test@gmail.com"
password = "password"

[jwt]
secret = "secret"
expired_in = 86400
token_key = "token"

[oidc]
login_redirect = "http://localhost:3000"
register_redirect = "http://localhost:3000/auth/complete"

[oidc.clients.google]
client_id = ""
client_secret = ""
issuer_url = ""
redirect_utl = ""

[rag]
qdrant_url = "http://localhost:6333"
gemini_api_key = ""
context_sample = 5
