on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
      - "**.md"
      - ".github/**"
  pull_request:
    branches: main
    paths-ignore:
      - "**.md"
      - ".github/**"

permissions:
  contents: read

jobs:
  clippy-fmt:
    name: Check Clippy and rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check Clippy
        run: cargo clippy --workspace -- -D warnings
      - name: Check rustfmt
        run: cargo fmt --all -- --check

  test:
    runs-on: ${{ matrix.os }}
    env:
      PGHOST: localhost
      PGDATABASE: test
      PGUSERNAME: test
      PGPASSWORD: test
      DATABASE_URL: postgres://test:test@localhost/test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - os: macos-latest
            target: x86_64-apple-darwin
            toolchain: stable
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            toolchain: stable
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
      - run: ${{ matrix.deps }}
      - uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres
      - run: psql ${{ steps.postgres.outputs.connection-uri }} -a -f schema.sql
      - uses: Swatinem/rust-cache@v2
      - name: Test
        shell: bash
        run: |
          export DATABASE_URL=${{ steps.postgres.outputs.connection-uri }}
          cargo test --target ${{ matrix.target }}
