on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image And Push
        run: |
          docker compose -f compose.build.yaml --profile frontend build
          docker compose -f compose.build.yaml --profile frontend push

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image And Push
        run: |
          docker compose -f compose.build.yaml --profile backend build
          docker compose -f compose.build.yaml --profile backend push

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}

      PG_USER: ${{ secrets.PG_USER }}
      PG_PASS: ${{ secrets.PG_PASS }}
      PG_DB: ${{ secrets.PG_DB }}

      BCRYPT_COST: ${{ secrets.BCRYPT_COST }}
      BCRYPT_SALT: ${{ secrets.BCRYPT_SALT }}

      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRED_IN: ${{ secrets.JWT_EXPIRED_IN }}

      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

      OIDC_LOGIN_REDIRECT: ${{ secrets.OIDC_LOGIN_REDIRECT }}
      OIDC_REGISTER_REDIRECT: ${{ secrets.OIDC_REGISTER_REDIRECT }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}
      GOOGLE_ISSUER_URL: ${{ secrets.GOOGLE_ISSUER_URL }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
      MICROSOFT_REDIRECT_URL: ${{ secrets.MICROSOFT_REDIRECT_URL }}
      MICROSOFT_ISSUER_URL: ${{ secrets.MICROSOFT_ISSUER_URL }}

      QDRANT_URL: ${{ secrets.QDRANT_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      RAG_CONTEXT_SAMPLE: ${{ secrets.RAG_CONTEXT_SAMPLE }}

      API_URL: ${{ secrets.API_URL }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean Container, Image And Prepare For Deploy
        run: docker compose -f compose.yaml -p blood-donation-system --profile deploy down --rmi all -v
      - name: Deploy Application
        run: docker compose -f compose.yaml -p blood-donation-system --profile deploy up -d
